import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import{BrowserRouter,Link,Route,Routes,useNavigate,useParams}from"react-router-dom";import{BookOpen,Landmark,Menu,Search,Sparkles,X}from"lucide-react";import"./styles.css";
const API=import.meta.env.VITE_API_URL||"http://localhost:5000/api";
async function api(p,o={}){
 const token=localStorage.getItem("toh_token");
 const r=await fetch(API+p,{...o,headers:{"Content-Type":"application/json",...(token?{"Authorization":"Bearer "+token}:{}),...(o.headers||{})}});
 let d={};
 try{d=await r.json()}catch{}
 if(!r.ok)throw Error(d.message||"Request failed");
 return d;
}
function useSession(){
 const[session,setSession]=useState(null);
 useEffect(()=>{const token=localStorage.getItem("toh_token");if(!token)return;api("/auth/me").then(setSession).catch(()=>{localStorage.removeItem("toh_token");setSession(null)})},[]);
 return session;
}
function Layout({children}){
 const[open,setOpen]=useState(false),session=useSession();
 const logout=()=>{localStorage.removeItem("toh_token");window.location.href="/"};
 return <div className="app"><header><Link to="/" className="brand"><span className="mark"><Landmark size={19}/></span>The Tales of History</Link><button className="mobileBtn" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?"open":""}><Link to="/">Explore</Link><Link to="/timeline">Timeline</Link><Link to="/about">About</Link>{session?<><span className="welcome">Hi, {session.user?.name?.split(" ")[0]||"Learner"}</span><button className="signin" onClick={logout}>Sign out</button></>:<Link to="/login" className="signin">Sign in</Link>}</nav></header>{children}<footer><div><b>The Tales of History</b><span>Read the past. Explore the story. Understand the world.</span></div><span>Interactive learning platform</span></footer></div>
}function Home(){const[t,setT]=useState([]),[q,setQ]=useState("");useEffect(()=>{api("/topics").then(setT)},[]);const f=t.filter(x=>String(x.title+" "+x.summary+" "+x.category+" "+x.era+" "+(x.tags||[])).toLowerCase().includes(q.toLowerCase()));return <Layout><main><section className="hero"><div><div className="eyebrow"><Sparkles size={15}/> HISTORY · MYTHOLOGY · LEARNING</div><h1>History is not just meant to be read. <em>It is meant to be explored.</em></h1><p>Discover civilizations, turning points, myths and people through stories, timelines, visual resources and an intelligent learning assistant.</p><div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search civilizations, events, myths..."/></div><div className="chips">{["Ancient India","International History","Greek Mythology","Norse Mythology"].map(x=><button onClick={()=>setQ(x)} key={x}>{x}</button>)}</div></div><div className="feature"><div className="featureImg" style={{backgroundImage:"url("+ (t[1]?.image||t[0]?.image)+")"}}/><div className="featureBody"><span className="label">FEATURED</span><h3>The stories behind the past</h3><p>Explore a growing library where evidence, storytelling and context meet.</p><Link to="/timeline">View timeline →</Link></div></div></section><section className="section"><div className="sectionHead"><div><span className="kicker">EXPLORE THE LIBRARY</span><h2>Start with a story</h2></div><span>{f.length} topics</span></div><div className="grid">{f.map(x=><Link className="card" to={"/topic/"+x.slug} key={x.slug}><div className="cardImg" style={{backgroundImage:"url("+x.image+")"}}/><div className="cardBody"><div className="meta"><span>{x.category}</span><span>{x.era}</span></div><h3>{x.title}</h3><p>{x.summary}</p><b>Explore topic →</b></div></Link>)}</div></section><section className="banner"><div><span className="kicker">PERSONAL HISTORY TUTOR</span><h2>Ask questions while you learn.</h2><p>Why did this happen? What changed after it? Turn any chapter into a conversation.</p></div><span className="pill"><Sparkles size={16}/> Context-aware learning assistant</span></section></main></Layout>}
function Topic(){const{slug}=useParams(),[t,setT]=useState(),[tab,setTab]=useState("overview"),[q,setQ]=useState(""),[a,setA]=useState(""),[notes,setNotes]=useState([]);useEffect(()=>{api("/topics/"+slug).then(setT)},[slug]);if(!t)return <Layout><div className="loading">Loading story…</div></Layout>;const ask=async()=>setA((await api("/ai/ask",{method:"POST",body:JSON.stringify({slug,question:q})})).answer);const getNotes=async()=>setNotes((await api("/ai/exam-notes",{method:"POST",body:JSON.stringify({slug})})).notes);return <Layout><main><div className="topicHero" style={{backgroundImage:"linear-gradient(90deg,rgba(17,18,22,.97),rgba(17,18,22,.40)),url("+t.image+")"}}><div><span className="label">{t.category} · {t.era}</span><h1>{t.title}</h1><p>{t.summary}</p></div></div><div className="topicLayout"><article><div className="tabs">{["overview","timeline","resources"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>{tab==="overview"&&<><h2>Story</h2><p className="story">{t.content}</p><h3>Key figures & concepts</h3><div className="figures">{(t.keyFigures||[]).map(x=><span key={x}>{x}</span>)}</div></>}{tab==="timeline"&&<div className="miniTimeline"><div><b>{t.startYear<0?Math.abs(t.startYear)+" BCE":t.startYear||"Early period"}</b><p>Beginning / early development</p></div><div><b>{t.endYear<0?Math.abs(t.endYear)+" BCE":t.endYear||"Later period"}</b><p>Later phase / transition</p></div></div>}{tab==="resources"&&<div className="resources"><h2>Sources & resources</h2>{(t.sources||[]).map(s=><a href={s} target="_blank" rel="noreferrer" key={s}>{s}</a>)}</div>}</article><aside className="tutor"><div className="tutorTop"><div><span className="kicker">AI LEARNING ASSISTANT</span><h3>Ask about this topic</h3></div><Sparkles/></div><textarea value={q} onChange={e=>setQ(e.target.value)} placeholder="Why did this happen? Explain simply…"/><button className="dark" onClick={ask}>Ask tutor</button><div className="suggestions">{["Explain this simply","Give me exam notes","What were the consequences?"].map(x=><button key={x} onClick={()=>setQ(x)}>{x}</button>)}</div>{a&&<div className="answer">{a}</div>}<button className="outline" onClick={getNotes}>Generate exam-focused notes</button>{notes.length>0&&<div className="answer">{notes.map(n=><p key={n}>• {n}</p>)}</div>}</aside></div></main></Layout>}
function Timeline(){const[t,setT]=useState([]);useEffect(()=>{api("/topics").then(setT)},[]);return <Layout><main className="section narrow"><span className="kicker">CHRONOLOGY</span><h1>Walk through the past</h1><p className="lead">A visual chronology across selected history topics.</p><div className="master">{t.filter(x=>x.startYear).sort((a,b)=>a.startYear-b.startYear).map(x=><Link to={"/topic/"+x.slug} key={x.slug}><span>{x.startYear<0?Math.abs(x.startYear)+" BCE":x.startYear}</span><div><b>{x.title}</b><small>{x.category} · {x.era}</small></div><span>→</span></Link>)}</div></main></Layout>}
function Login(){
 const nav=useNavigate(),[mode,setMode]=useState("login"),[form,setForm]=useState({name:"",email:"",password:"",confirm:""}),[err,setErr]=useState(""),[busy,setBusy]=useState(false);
 const submit=async e=>{e.preventDefault();setErr("");if(mode==="register"&&form.password!==form.confirm){setErr("Passwords do not match.");return}if(form.password.length<6){setErr("Password must be at least 6 characters.");return}setBusy(true);try{const d=await api("/auth/"+mode,{method:"POST",body:JSON.stringify({name:form.name.trim(),email:form.email.trim(),password:form.password})});localStorage.setItem("toh_token",d.token);nav("/");window.location.reload()}catch(x){setErr(x.message)}finally{setBusy(false)}};
 return <Layout><main className="auth"><div className="authCard"><span className="kicker">YOUR LEARNING SPACE</span><h1>{mode==="login"?"Welcome back":"Create your account"}</h1><p>{mode==="login"?"Sign in to continue your learning journey.":"Create an account to save your learning progress."}</p><form onSubmit={submit}>{mode==="register"&&<input required minLength="2" placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>}<input required type="email" placeholder="Email address" autoComplete="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input required minLength="6" type="password" placeholder="Password (6+ characters)" autoComplete={mode==="login"?"current-password":"new-password"} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>{mode==="register"&&<input required minLength="6" type="password" placeholder="Confirm password" autoComplete="new-password" value={form.confirm} onChange={e=>setForm({...form,confirm:e.target.value})}/>} {err&&<small className="error">{err}</small>}<button className="dark" disabled={busy}>{busy?(mode==="login"?"Signing in…":"Creating account…"):(mode==="login"?"Sign in":"Create account")}</button></form><button className="switch" onClick={()=>{setErr("");setMode(mode==="login"?"register":"login");setForm({name:"",email:form.email,password:"",confirm:""})}}>{mode==="login"?"New here? Create an account":"Already have an account? Sign in"}</button></div></main></Layout>
}function About(){return <Layout><main className="section narrow"><span className="kicker">THE IDEA</span><h1>Learn the past as a connected story.</h1><p className="lead">The Tales of History brings narratives, visual resources, chronology and contextual learning together in one focused environment.</p><div className="aboutGrid">{["Structured library","Interactive timelines","Contextual tutor","Exam preparation"].map(x=><div className="aboutCard" key={x}><BookOpen/><h3>{x}</h3><p>Designed to make historical learning easier to navigate, revisit and question.</p></div>)}</div></main></Layout>}
function App(){return <Routes><Route path="/" element={<Home/>}/><Route path="/topic/:slug" element={<Topic/>}/><Route path="/timeline" element={<Timeline/>}/><Route path="/login" element={<Login/>}/><Route path="/about" element={<About/>}/></Routes>}createRoot(document.getElementById("root")).render(<BrowserRouter><App/></BrowserRouter>);